import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jonathanthompson' at '9/27/16 6:03 PM' with Gradle 2.12
 *
 * @author jonathanthompson, @date 9/27/16 6:03 PM
 */
public class LibraryTest {

}
