/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonathanthompson' at '9/3/16 9:24 PM' with Gradle 2.12
 *
 * @author jonathanthompson, @date 9/3/16 9:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
